aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  ses:
    region: ${AWS_SES_REGION}
    email:
      sender-name: ${EMAIL_SENDER_NAME}
      source: ${EMAIL_SOURCE}
